erDiagram
        CUSTOMER }|..|{ DELIVERY-ADDRESS:has
        CUSTOMER ||--o{ ORDER:places
        CUSTOMER ||--o{ INVOICE: "liable for"
        DELIVERY-ADDRESS || --o{ ORDER:receives
        INVOICE || --o{ORDER :receives
        ORDER || --|{ ORDER-ITEM :includes
        PRODUCT-CATEGORY ||--|{PRODUCT:contains
        PRODUCT ||--o{ ORDER-ITEM:"ordered in"
        